version: '3'
services:
  frontend:
    build: ./expiry-tracker
    ports:
      - "3000:3000"
    volumes:
      - ./expiry-tracker:/app
    working_dir: /app
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - ./backend/.env
