apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 222634395624.dkr.ecr.ap-northeast-1.amazonaws.com/expiry-tracker-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: LINE_ACCESS_TOKEN
              value: "xxxxx"
            - name: LINE_CHANNEL_SECRET
              value: "xxxxx"
            - name: LINE_USER_ID
              value: "xxxxx"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP

